version: '3.9'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db
    command: --quiet
    restart: always

  app:
    build:
      context: .
      dockerfile: ./cmd/app/Dockerfile
    image: burp_junior:latest
    ports:
      - 8080:8080
      - 8000:8000
    restart: always
    depends_on:
      - mongo

volumes:
  mongo-data:
